import Head from 'next/head';
import Link from 'next/link';
import { ArrowUpRight, Music2, Youtube } from 'lucide-react';

export default function MusicIndex() {
  return (
    <><Head><title>Música — RubnPneal</title><meta name="description" content="Música publicada y trabajos musicales de RubnPneal." /></Head><div className="bg-[#0b0b0b] text-[#f5f2e8]"><section className="mx-auto max-w-[1440px] px-5 py-20 sm:px-8 sm:py-28 lg:px-12"><p className="eyebrow text-white/45">Composición · Producción · Canciones</p><h1 className="mt-5 max-w-5xl text-[clamp(4rem,10vw,9rem)] font-semibold leading-[0.85] tracking-[-0.065em]">Música.</h1><p className="mt-8 max-w-2xl text-lg leading-8 text-white/55">Una selección de trabajos publicados. Elige plataforma para escuchar la discografía o ver las piezas musicales en vídeo.</p></section><section className="mx-auto grid max-w-[1440px] gap-px bg-white/15 px-0 md:grid-cols-2"><Link href="/music/spotify" className="group flex min-h-[430px] flex-col justify-between bg-[#121212] p-8 transition-colors hover:bg-[#181818] sm:p-10 lg:p-12"><div className="flex items-start justify-between"><Music2 className="h-8 w-8 text-[#1ed760]" /><ArrowUpRight className="h-5 w-5 transition-transform group-hover:-translate-y-1 group-hover:translate-x-1" /></div><div><p className="eyebrow text-white/40">Streaming</p><h2 className="display-title mt-3 text-6xl sm:text-7xl">Spotify</h2><p className="mt-4 max-w-md text-base leading-7 text-white/50">Canciones publicadas y acceso al perfil de artista.</p></div></Link><Link href="/music/youtube" className="group flex min-h-[430px] flex-col justify-between bg-[#151515] p-8 transition-colors hover:bg-[#1b1b1b] sm:p-10 lg:p-12"><div className="flex items-start justify-between"><Youtube className="h-8 w-8 text-[#ff0033]" /><ArrowUpRight className="h-5 w-5 transition-transform group-hover:-translate-y-1 group-hover:translate-x-1" /></div><div><p className="eyebrow text-white/40">Vídeo musical</p><h2 className="display-title mt-3 text-6xl sm:text-7xl">YouTube</h2><p className="mt-4 max-w-md text-base leading-7 text-white/50">Publicaciones musicales y piezas audiovisuales asociadas a las canciones.</p></div></Link></section></div></>
  );
}
